spring:
  application:
    name: kafka-streams-poc

  datasource:
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 10
    url: jdbc:postgresql://localhost:5432/poc
    username: poc_admin
    password: poc_admin_pwd

  jpa:
    show-sql: true
    generate-ddl: false

  kafka:
    client-id: kafka-streams-poc
    bootstrap-servers: localhost:19092
#    consumer:
#      #key-deserializer: org.apache.kafka.connect.json.JsonDeserializer
#      #value-deserializer: org.apache.kafka.connect.json.JsonDeserializer
#      key-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
#      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    streams:
      application-id: applications-stream
