server:
  port: 8081

spring:
  application:
    name: kafka-streams-consumer-poc

  kafka:
    client-id: kafka-streams-consumer-poc
    bootstrap-servers: localhost:19092
#    consumer:
#      #key-deserializer: org.apache.kafka.connect.json.JsonDeserializer
#      #value-deserializer: org.apache.kafka.connect.json.JsonDeserializer
#      key-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
#      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    streams:
      application-id: applications-consumer-stream
